server:
  forward-headers-strategy: framework
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
spring:
  application:
    name: why_price
  config:
    import: optional:file:.env[.properties]
  ai:
    openai:
      api-key: notUsed #사용하지않지만 항목이 있어야 에러가 안남,openAiChatModel을 개조해서 써서 이럼
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_ID}
    password: ${MYSQL_KEY}
  jpa:
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        default_batch_fetch_size: 100
        show_sql: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
      ddl-auto: update

