###1.가입(2번누르면 중복체크)
POST {{baseApi}}/api/member
Content-Type: application/json

{
  "name": "abc"
}
###2.멤버주식추가(삼전)
POST {{baseApi}}/api/member/stock
Content-Type: application/json

{
  "memberName": "abc",
  "stockCrno": "130111-0006246",
  "stockName": "삼성전자"
}
###2.멤버주식추가(LG)
POST {{baseApi}}/api/member/stock
Content-Type: application/json

{
  "memberName": "abc",
  "stockCrno": "110111-2487050",
  "stockName": "LG전자"
}

###3.멤버주식삭제(삼전)
DELETE {{baseApi}}/api/member/stock
Content-Type: application/json

{
  "memberName": "abc",
  "stockCrno": "130111-0006246",
  "stockName": "삼성전자"
}

###4.멤버주식조회
GET {{baseApi}}/api/member/stock?memberName=abc
Content-Type: application/json


###5.변동성체크
GET {{baseApi}}/api/member/stock/volatility?memberName=abc
Content-Type: application/json

